### ISSUE TITLE
I dont trust this Fluster

### ISSUE THREAD

**Issue by Skeleton19** [cereralwithmilk/Fluster#2]
![2023-10-28_23-47-52](https://github.com/cereralwithmilk/Fluster/assets/50092873/1f08fa80-ebc9-4c9a-94ff-50042fe985c0)
Left part - this Fluster, right part - original Fluster. What is Exela Corporation? Original Fluster dont have RCData. What this is data doing?

**Comment by zxcworldru** [comment]
Stealer https://github.com/quicaxd/Exela-V2.0
